name: Monitor Workflow Runs

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]

jobs:
  monitor:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'cancelled'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate workflow summary
        run: |
          echo "# Workflow Run Summary" > summary.md
          echo "" >> summary.md
          echo "**Workflow:** ${{ github.event.workflow_run.name }}" >> summary.md
          echo "**Status:** ${{ github.event.workflow_run.conclusion }}" >> summary.md
          echo "**Branch:** ${{ github.event.workflow_run.head_branch }}" >> summary.md
          echo "**Commit:** ${{ github.event.workflow_run.head_sha }}" >> summary.md
          echo "**Run ID:** ${{ github.event.workflow_run.id }}" >> summary.md
          echo "**URL:** ${{ github.event.workflow_run.html_url }}" >> summary.md

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: workflow-summary-${{ github.event.workflow_run.id }}
          path: summary.md
          retention-days: 30

      - name: Comment on PR (if applicable)
        if: github.event.workflow_run.event == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('summary.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
